# Generated by Django 4.0.3 on 2023-03-05 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('dui', models.CharField(max_length=10, verbose_name='DUI')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('estadoCivil', models.CharField(max_length=10, verbose_name='estadoCivil')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('fechaNaci', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('direccion', models.TextField(max_length=300, verbose_name='Direccion')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.cargo', verbose_name='Cargo')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['idempleado'],
            },
        ),
    ]
