# Generated by Django 4.0.3 on 2023-03-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='imagen',
            field=models.ImageField(default='', upload_to='', verbose_name='Foto'),
        ),
    ]
