# Generated by Django 4.0.3 on 2023-03-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0002_material_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Foto'),
        ),
    ]
